# EEL770 - Sistemas Operacionais @ UFRJ
# Macros
cc = gcc
args = -Wall
flags = -pthread -lm

# Makefile
all: unisex

unisex:
	$(cc) $(args) -o unisex unisex.c $(flags)

clean:
	rm -f *.o unisex
# End Makefile
