# EEL770 - Sistemas Operacionais @ UFRJ
# Macros
cc = gcc
args = -Wall
flags = -pthread

# Makefile
all: river

river:
	$(cc) $(args) -o river river.c $(flags)

clean:
	rm -f *.o river
# End Makefile
