# EEL770 - Sistemas Operacionais @ UFRJ
# Macros
cc = gcc
args = -Wall
flags = -pthread

# Makefile
all: party

party:
	$(cc) $(args) -o party party.c $(flags)

clean:
	rm -f *.o party
# End Makefile
